services:
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  vue-app:
    image: node:latest
    container_name: vue-app
    working_dir: /app
    volumes:
      - ./website:/app
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm run serve"

volumes:
  mongo-data: